#!/usr/bin/env bash
set -euo pipefail

DOTFILES="$HOME/Dotfiles"
ACTIVE_THEME="$1"

if [[ "$ACTIVE_THEME" == "null" || -z "$ACTIVE_THEME" ]]; then
    echo "Error: No theme specified"
    exit 1
fi

THEME_FILE="$DOTFILES/themes/$ACTIVE_THEME.json"
DEFAULTS_FILE="$DOTFILES/themes/defaults.json"

if [[ ! -f "$THEME_FILE" ]]; then
    echo "Error: Theme '$ACTIVE_THEME' not found (missing $THEME_FILE)"
    exit 1
fi

if ! command -v jq &>/dev/null; then
    echo "Error: jq is not installed"
    exit 1
fi

# Merge defaults with theme overrides — one jq parse for all token lookups
MERGED=$(jq -s '.[0] * .[1]' "$DEFAULTS_FILE" "$THEME_FILE")

get_palette() { echo "$MERGED" | jq -r ".palette.$1"; }
get_role() { echo "$MERGED" | jq -r ".palette[.roles.$1]"; }
get_font() { echo "$MERGED" | jq -r ".fonts.$1"; }
get_value() { echo "$MERGED" | jq -r ".values.$1"; }
get_spacing() { echo "$MERGED" | jq -r ".spacing.$1"; }
get_fontsize() { echo "$MERGED" | jq -r ".fontSizes.$1"; }

strip_hash() { echo "${1#\#}"; }
capitalize() { echo "$1" | sed 's/.*/\u&/'; }

mkdir -p "$DOTFILES/quickshell"
mkdir -p "$DOTFILES/theme"

# Generate bash/colors
hex_to_rgb() {
    local hex="${1#\#}"

    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))

    printf '%s;%s;%s' "$r" "$g" "$b"
}

mkdir -p "$DOTFILES/bash"

BASH_ACCENT="$(hex_to_rgb "$(get_role accent)")"
BASH_TEXT="$(hex_to_rgb "$(get_palette text)")"
BASH_MUTED="$(hex_to_rgb "$(get_role muted)")"
BASH_BLUE="$(hex_to_rgb "$(get_palette blue)")"
BASH_GREEN="$(hex_to_rgb "$(get_palette green)")"
BASH_RED="$(hex_to_rgb "$(get_palette red)")"
BASH_YELLOW="$(hex_to_rgb "$(get_palette yellow)")"

cat >"$DOTFILES/bash/colors" <<EOF
# Generated by build-theme.sh
# Do not edit manually.

RESET='\e[0m'

ACCENT='\e[38;2;${BASH_ACCENT}m'
TEXT='\e[38;2;${BASH_TEXT}m'
MUTED='\e[38;2;${BASH_MUTED}m'

BLUE='\e[38;2;${BASH_BLUE}m'
GREEN='\e[38;2;${BASH_GREEN}m'
RED='\e[38;2;${BASH_RED}m'
YELLOW='\e[38;2;${BASH_YELLOW}m'

LS_DIR="38;2;${BASH_BLUE}"
LS_LINK="38;2;${BASH_ACCENT}"
LS_EXEC="38;2;${BASH_GREEN}"

PROMPT_USER="\$ACCENT"
PROMPT_HOST="\$GREEN"
PROMPT_DIR="\$BLUE"
PROMPT_SYMBOL="\$ACCENT"
EOF

# Generate Theme.qml
cat >"$DOTFILES/quickshell/Theme.qml" <<EOF
import QtQuick
pragma Singleton

QtObject {
    id: theme

    // SEMANTIC COLORS
    property color accent:  "$(get_role accent)"
    property color warning: "$(get_role warning)"
    property color success: "$(get_role success)"
    property color info:    "$(get_role info)"
    property color muted:   "$(get_role muted)"

    // BACKGROUND LAYERS
    property color base:         "#CC$(strip_hash "$(get_palette base)")"
    property color baseSolid:    "$(get_palette base)"
    property color mantle:       "#E6$(strip_hash "$(get_palette mantle)")"
    property color mantleSolid:  "$(get_palette mantle)"

    // TEXT
    property color text:     "$(get_palette text)"
    property color subtext1: "$(get_palette subtext1)"

    // SURFACES
    property color surface0: "$(get_palette surface0)"
    property color surface1: "$(get_palette surface1)"
    property color surface2: "$(get_palette surface2)"

    // OVERLAYS
    property color overlay0: "$(get_palette overlay0)"
    property color overlay1: "$(get_palette overlay1)"

    // FULL PALETTE
    property color mauve:    "$(get_palette mauve)"
    property color lavender: "$(get_palette lavender)"
    property color peach:    "$(get_palette peach)"
    property color green:    "$(get_palette green)"
    property color red:      "$(get_palette red)"
    property color yellow:   "$(get_palette yellow)"
    property color blue:     "$(get_palette blue)"
    property color teal:     "$(get_palette teal)"
    property color pink:     "$(get_palette pink)"
    property color white:    "$(get_palette white)"
    property color black:    "$(get_palette black)"

    // ROUNDING
    property int radius:    $(get_value radius)
    property int radiusAlt: $(get_value radiusAlt)

    // FONTS
    property string fontMain: "$(get_font main)"
    property string fontMono: "$(get_font mono)"

    // SIZES AND GAPS
    property int borderWidth: $(get_value borderWidth)
    property int gap:         $(get_value gap)

    // SPACINGS
    property int spacingXs: $(get_spacing xs)
    property int spacingSm: $(get_spacing sm)
    property int spacingMd: $(get_spacing md)
    property int spacingLg: $(get_spacing lg)
    property int spacingXl: $(get_spacing xl)

    // MODULE DIMENSIONS
    property int moduleWidth:  40
    property int moduleHeight: SettingsManager.barHeight < 40 ? SettingsManager.barHeight : 40

    // FONT SIZES
    property int fontSizeHuge:  $(get_fontsize huge)
    property int fontSizeXxl:   $(get_fontsize xxl)
    property int fontSizeXl:    $(get_fontsize xl)
    property int fontSizeLg:    $(get_fontsize lg)
    property int fontSizeMd:    $(get_fontsize md)
    property int fontSizeBase:  $(get_fontsize base)
    property int fontSizeSm:    $(get_fontsize sm)
    property int fontSizeXs:    $(get_fontsize xs)
    property int fontSizeXxs:   $(get_fontsize xxs)
    property int fontSizeTiny:  $(get_fontsize tiny)
    property int fontSizeMicro: $(get_fontsize micro)
}
EOF

# Generate Hyprland theme
cat >"$DOTFILES/hypr/theme.lua" <<EOF
local theme = {
    base       = "rgb($(strip_hash "$(get_palette base)"))",
    text       = "rgb($(strip_hash "$(get_palette text)"))",
    accent     = "rgb($(strip_hash "$(get_role accent)"))",
    surface1   = "rgb($(strip_hash "$(get_palette surface1)"))",
    bgalpha    = "0xee$(strip_hash "$(get_palette base)")",
    mutedalpha = "0xaa$(strip_hash "$(get_palette surface1)")",

    rounding = $(get_value radius),
    roundingAlt = $(get_value radiusAlt),
}

return theme
EOF

# Generate Alacritty theme
cat >"$DOTFILES/theme/theme.toml" <<EOF
[colors.primary]
background = "0x$(strip_hash "$(get_palette base)")"
foreground = "0x$(strip_hash "$(get_palette text)")"

[colors.normal]
black   = "0x$(strip_hash "$(get_palette black)")"
red     = "0x$(strip_hash "$(get_palette red)")"
green   = "0x$(strip_hash "$(get_palette green)")"
yellow  = "0x$(strip_hash "$(get_palette yellow)")"
blue    = "0x$(strip_hash "$(get_palette blue)")"
magenta = "0x$(strip_hash "$(get_role accent)")"
cyan    = "0x$(strip_hash "$(get_palette teal)")"
white   = "0x$(strip_hash "$(get_palette text)")"

[colors.bright]
black   = "0x$(strip_hash "$(get_palette surface1)")"
red     = "0x$(strip_hash "$(get_palette red)")"
green   = "0x$(strip_hash "$(get_palette green)")"
yellow  = "0x$(strip_hash "$(get_palette yellow)")"
blue    = "0x$(strip_hash "$(get_palette blue)")"
magenta = "0x$(strip_hash "$(get_palette pink)")"
cyan    = "0x$(strip_hash "$(get_palette teal)")"
white   = "0x$(strip_hash "$(get_palette white)")"

[font.normal]
family = "$(get_font mono)"
style  = "$(capitalize "$(get_font style)")"
EOF

# Generate fastfetch config
ACCENT=$(get_role accent)
FG=$(get_palette white)
MUTED=$(get_role muted)

cat >"$DOTFILES/fastfetch/config.jsonc" <<EOF
{
  "\$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",

  "logo": {
    "type": "file",
    "source": "$HOME/.config/fastfetch/tissla.txt",
    "color": {
      "1": "$ACCENT",
      "2": "$FG",
      "3": "$MUTED"
    }
  },

  "display": {
    "separator": " : ",
    "color": {
      "keys":      "$ACCENT",
      "title":     "$ACCENT",
      "separator": "$MUTED",
      "output":    "$FG"
    },
    "key": { "width": 12 }
  },

  "modules": [
    { "type": "title" },

    "separator",

    { "type": "os",     "key": "OS",     "keyColor": "$ACCENT", "outputColor": "$FG" },
    { "type": "kernel", "key": "Kernel", "keyColor": "$ACCENT", "outputColor": "$FG" },
    { "type": "uptime", "key": "Uptime", "keyColor": "$ACCENT", "outputColor": "$FG" },
    { "type": "wm",     "key": "WM",     "keyColor": "$ACCENT", "outputColor": "$FG" },
    { "type": "theme",  "key": "Theme",  "keyColor": "$ACCENT", "outputColor": "$FG" },
    { "type": "font",   "key": "Font",   "keyColor": "$ACCENT", "outputColor": "$FG" },
    { "type": "cpu",    "key": "CPU",    "keyColor": "$ACCENT", "outputColor": "$FG" },
    { "type": "gpu",    "key": "GPU",    "keyColor": "$ACCENT", "outputColor": "$FG" },
    { "type": "memory", "key": "Mem",    "keyColor": "$ACCENT", "outputColor": "$FG" },
    { "type": "disk",   "key": "Disk",   "keyColor": "$ACCENT", "outputColor": "$FG" },

    "break",

    { "type": "colors", "symbol": "block", "paddingLeft": 1, "block": { "width": 3 } }
  ]
}
EOF

# Generate Rofi theme
cat >"$DOTFILES/theme/theme.rasi" <<EOF
* {
    bg:          $(get_palette base)E6;
    bg-alt:      $(get_palette mantle)E6;
    fg:          $(get_palette text);
    primary:     $(get_role accent);
    error:       $(get_palette red);
    muted:       $(get_role muted);
    font-main:   "$(get_font main) $(capitalize "$(get_font style)") $(get_font size)";
    font-search: "$(get_font mono) $(($(get_font size) + 4))";
}
EOF
