##windowrule = match:class chromium, opacity 0.9 0.85
##windowrule = match:class steam, opacity 0.9 0.85
#

windowrule = match:class ^(gamescope)$, fullscreen_state 2 2
windowrule = match:class gamescope, fullscreen_state 2 2
